apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    uid: postgresql
    url: host.docker.internal:5432
    user: acars
    secureJsonData:
      password: acars
    jsonData:
      database: acars
      sslmode: disable
      postgresVersion: 1500
